### ISSUE TITLE
I'm getting error

### ISSUE THREAD

**Issue by scriptcim** [IceTimux/SMTP-Bootstrap-Contact-Form#1]
Hello dear
I'm getting error
Error!There was a problem delivering the message.

**Comment by IceTimux** [comment]
Are you using SMTP? if so, are your credentials correct? Are you using SSL?

**Comment by scriptcim** [comment]
Hello IceTimux

I made the necessary arrangements index.php

// Set up SMTP  
    $mail->IsSMTP();                // Sets up a SMTP connection  
    $mail->SMTPAuth = true;         // Connection with the SMTP does require authorization    
    $mail->SMTPSecure = "";      // Connect using a TLS connection  
    $mail->Host = "smtp.scriptportali.com";  //Gmail SMTP server address
    $mail->Port = 587;  //Gmail SMTP port
    $mail->Encoding = '7bit';
    
    // Authentication  
    $mail->Username   = "info@scriptportali.com"; // Your full Gmail address
    $mail->Password   = "8243SMzc:"; // Your Gmail password
      
    // Compose
    $mail->SetFrom($_POST['emailid'], $_POST['fullname']);
    $mail->AddReplyTo($_POST['emailid'], $_POST['fullname']);
    $mail->Subject = "New Contact Form Enquiry";      // Subject (which isn't required)  
    $mail->MsgHTML($message);
 
    // Send To  
    $mail->AddAddress("info@scriptportali.com", "Mr. Example"); // Where to send it - Recipient
    $result = $mail->Send();		// Send!  
	$message = $result ? '<div class="alert alert-success" role="alert"><strong>Success!</strong>Message Sent Successfully!</div>' : '<div class="alert alert-danger" role="alert"><strong>Error!</strong>There was a problem delivering the message.</div>';  

	unset($mail);

http://scriptportali.com/iletisim1/

It gave this error: Error!There was a problem delivering the message.

**Comment by IceTimux** [comment]
can you try

`$mail->SMTPSecure = "null"; // Connect using a TLS connection`
?

**Comment by scriptcim** [comment]
hello
İm add null
Unfortunately, the same problem :(
$mail->SMTPSecure = "null"; // Connect using a TLS connection

**Comment by IceTimux** [comment]
This is an authentication error that is occurring. Please revise your credentials. Try commenting out the

`$mail->SMTPSecure = "null";` 

see if that helps.

**Comment by scriptcim** [comment]
Hello
This is another form of communication: http://scriptportali.com/iletisim It works without problems

All settings do not work, although it is true http://scriptportali.com/iletisim1/  I loved

**Comment by IceTimux** [comment]
I am having trouble loading those links. This is a authentication problem. For more information checkout the PHPMailer docs: https://github.com/PHPMailer/PHPMailer

**Comment by scriptcim** [comment]
Hello
Thanks for your help
Thanks for your time
I want to do research on error
                                        bye bye
