### ISSUE TITLE
Question about SMTP-Bootstrap-Contact-Form

### ISSUE THREAD

**Issue by Rutgrrr** [IceTimux/SMTP-Bootstrap-Contact-Form#2]
Hello Timothy,
I am using your script and it works perfect! Thanks.

Just one question:
I have a one page website and the mailform is at the bottom of this site, after submitting the email is send.
But also after submitting the page jumps to the beginning (top) what means that the person that pressed the submit button never see the message "email is send" or the error message.
Unless they scroll down to the contact section.

Is there a way that after submitting the form the page stays at the same position?

Kind Regards,  Rutger

**Comment by IceTimux** [comment]
The reason it goes to the top is because when you submit the form it makes a POST request which refreshes the page. A good way is to use Ajax to send a POST request to the php script instead.

**Comment by Rutgrrr** [comment]
Thanks,

You don't have any example how to do this with ajax.

**Comment by IceTimux** [comment]
Nope. It's easy with jQuery. You make it so when you click (onlick) on the send button, it prevents default (e.preventdefault) and then it takes all the input from the input elements and store them in a variable. You then call a jQuery ajax POST to the php file (in this case index.php) and pass the variable through. In php you capture the variable with the $_POST global variable. Preform checks if you need and then based on that, send the message and return a response. In your JS file or part you then take that response and display it to the user.

**Comment by Rutgrrr** [comment]
Hmmmm,

Thanks Timothy,
I see what I can do, I'm a noob with AJAX so I will see if I can find something on the internet.

Thanks anyway.
